name: Example Analytics Engine CI

on:
  push:
    branches: ['devin/**', 'main']
  pull_request:
    branches: ['main']
    paths:
      - 'examples/analytics-engine/**'

jobs:
  example-ci:
    name: Examples/Analytics-Engine Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/analytics-engine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Prettier check
        run: npm run format:check

      - name: Build
        run: npm run build

      - name: Generate Docs
        run: npm run docs

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Deno fmt check
        run: deno fmt --check supabase/functions

      - name: Deno lint
        run: deno lint supabase/functions
